# Use the AWS Lambda Python Docker image
FROM public.ecr.aws/lambda/python:3.8

# Copy python script and requirements file to the docker image
COPY lambda_function.py ${LAMBDA_TASK_ROOT}
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Upgrade pip and install required python packages
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Set the CMD to your handler (this is specific to AWS Lambda Docker images)
CMD [ "lambda_function.lambda_handler" ]
